name: heroku and testing

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "selenium-tp"
          heroku_email: "martin.miranda.2004@gmail.com"

